TOKENIZER_VOCAB_SIZE:  1000
SEQUENCE_MAX_LENGTH: 75
BATCH_SIZE: 128
NUM_EPOCHS: 10
TRAIN_TEST_SPLIT: 0.2
VALIDATION_SPLIT: 0.2
TAIL_SIZE: 10

# augmentation
## sentence variations
AUG:
  SENTENCE_VAR:
    TOTAL: 100
    VARS_PER: 3
    MUTATION_PROB: 0.1
  SENTENCE_NEG:
    TOTAL: 150
  SHUFFLE:
    TOTAL: 100
  GARBAGE:
    TOTAL: 100
    LENGTH_LOWER_BOUND: 0
    LENGTH_UPPER_BOUND: 10
  VOCAB_GARBAGE:
    TOTAL: 100
    TOPK: 50